# Generated by Django 3.2.13 on 2022-06-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("مرد", "MALE"), ("زن", "FEMALE")], max_length=10
            ),
        ),
    ]
