# Generated by Django 3.2.13 on 2022-06-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[("آنلاین", "Online"), ("آفلاین", "Offline")],
                default="افلاین",
                max_length=12,
            ),
        ),
    ]
