# Generated by Django 3.2.14 on 2022-08-04 05:48

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CartPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('tracing_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='cart_pay/')),
                ('description', models.TextField(blank=True)),
                ('cart_number', models.CharField(max_length=16)),
                ('origin_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.origincart')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.tariff')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
