# Generated by Django 3.2.14 on 2022-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_cartpay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpay',
            name='status',
            field=models.CharField(choices=[('waiting', ' در انتظار تایید'), ('accepted', 'تایید شده'), ('rejected', ' تایید نشد')], default='waiting', max_length=15),
        ),
    ]
