# Generated by Django 3.2.14 on 2022-08-04 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_cartpay_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.tariff')),
            ],
        ),
    ]
