# Generated by Django 3.2.13 on 2022-06-30 01:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configbase",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
