# Generated by Django 3.2.13 on 2022-08-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact',
        ),
    ]
